<?php


namespace app\widgets;


use yii\base\Widget;

class ButtonWidget extends Widget
{
    public $text;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        // $this->text = 'Submit';
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return '<button>'. $this->text .'</button>';
    }

}